version: '3'
services:
  todoback:
    image: todobackend
    restart: on-failure
    ports:
      - 3001:3001

  todofront:
    image: todofrontend
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback

  todotests:
    image: todotests
    restart: on-failure
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront

  

  
